import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for Zakeer Sadikeen's portfolio website",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white dark:bg-black px-4 sm:px-6 md:px-8 py-16 sm:py-20">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl sm:text-4xl font-semibold mb-8 text-black dark:text-white">Privacy Policy</h1>
        
        <div className="prose prose-zinc dark:prose-invert max-w-none">
          <p className="text-sm text-zinc-600 dark:text-zinc-400 mb-6">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4 text-black dark:text-white">Information We Collect</h2>
            <p className="text-zinc-700 dark:text-zinc-300 mb-4">
              This website uses Google Analytics 4 to collect anonymous usage statistics. 
              We collect information such as:
            </p>
            <ul className="list-disc list-inside text-zinc-700 dark:text-zinc-300 space-y-2 mb-4 ml-4">
              <li>Pages visited and time spent on pages</li>
              <li>Device and browser information</li>
              <li>General geographic location (country/city level)</li>
              <li>Referral sources</li>
            </ul>
            <p className="text-zinc-700 dark:text-zinc-300">
              We do not collect personally identifiable information (PII) through Google Analytics.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4 text-black dark:text-white">How We Use Information</h2>
            <p className="text-zinc-700 dark:text-zinc-300 mb-4">
              The information collected is used solely to:
            </p>
            <ul className="list-disc list-inside text-zinc-700 dark:text-zinc-300 space-y-2 ml-4">
              <li>Understand how visitors use the website</li>
              <li>Improve website performance and user experience</li>
              <li>Analyze traffic patterns</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4 text-black dark:text-white">Google Analytics</h2>
            <p className="text-zinc-700 dark:text-zinc-300 mb-4">
              This website uses Google Analytics, a web analytics service provided by Google, Inc. 
              Google Analytics uses cookies to analyze how visitors use this site. 
              The information generated by the cookie about your use of the website 
              (including your IP address) will be transmitted to and stored by Google.
            </p>
            <p className="text-zinc-700 dark:text-zinc-300 mb-4">
              You can opt-out of Google Analytics by installing the{" "}
              <a 
                href="https://tools.google.com/dlpage/gaoptout" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                Google Analytics Opt-out Browser Add-on
              </a>.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4 text-black dark:text-white">Cookies</h2>
            <p className="text-zinc-700 dark:text-zinc-300">
              This website uses cookies to enhance user experience and for analytics purposes. 
              By using this website, you consent to the use of cookies in accordance with this policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold mb-4 text-black dark:text-white">Contact</h2>
            <p className="text-zinc-700 dark:text-zinc-300">
              If you have any questions about this Privacy Policy, please contact us at{" "}
              <a 
                href="mailto:zakeermohomed95@gmail.com"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                zakeermohomed95@gmail.com
              </a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}

